// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queue

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue[T] {
	mock := &MockQueue[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue[T any] struct {
	mock.Mock
}

type MockQueue_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockQueue[T]) EXPECT() *MockQueue_Expecter[T] {
	return &MockQueue_Expecter[T]{mock: &_m.Mock}
}

// Pop provides a mock function for the type MockQueue
func (_mock *MockQueue[T]) Pop(ctx context.Context, queue string) (T, error) {
	ret := _mock.Called(ctx, queue)

	if len(ret) == 0 {
		panic("no return value specified for Pop")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (T, error)); ok {
		return returnFunc(ctx, queue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) T); ok {
		r0 = returnFunc(ctx, queue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, queue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_Pop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pop'
type MockQueue_Pop_Call[T any] struct {
	*mock.Call
}

// Pop is a helper method to define mock.On call
//   - ctx context.Context
//   - queue string
func (_e *MockQueue_Expecter[T]) Pop(ctx interface{}, queue interface{}) *MockQueue_Pop_Call[T] {
	return &MockQueue_Pop_Call[T]{Call: _e.mock.On("Pop", ctx, queue)}
}

func (_c *MockQueue_Pop_Call[T]) Run(run func(ctx context.Context, queue string)) *MockQueue_Pop_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Pop_Call[T]) Return(v T, err error) *MockQueue_Pop_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockQueue_Pop_Call[T]) RunAndReturn(run func(ctx context.Context, queue string) (T, error)) *MockQueue_Pop_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockQueue
func (_mock *MockQueue[T]) Push(ctx context.Context, queue string, value T) error {
	ret := _mock.Called(ctx, queue, value)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, T) error); ok {
		r0 = returnFunc(ctx, queue, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockQueue_Push_Call[T any] struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - queue string
//   - value T
func (_e *MockQueue_Expecter[T]) Push(ctx interface{}, queue interface{}, value interface{}) *MockQueue_Push_Call[T] {
	return &MockQueue_Push_Call[T]{Call: _e.mock.On("Push", ctx, queue, value)}
}

func (_c *MockQueue_Push_Call[T]) Run(run func(ctx context.Context, queue string, value T)) *MockQueue_Push_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 T
		if args[2] != nil {
			arg2 = args[2].(T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueue_Push_Call[T]) Return(err error) *MockQueue_Push_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Push_Call[T]) RunAndReturn(run func(ctx context.Context, queue string, value T) error) *MockQueue_Push_Call[T] {
	_c.Call.Return(run)
	return _c
}
