// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package migration

import (
	"github.com/hashicorp/go-version"
	"github.com/mikelear/leartech-bus-common/pkg/mongo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMigrationInterface creates a new instance of MockMigrationInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrationInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrationInterface {
	mock := &MockMigrationInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMigrationInterface is an autogenerated mock type for the MigrationInterface type
type MockMigrationInterface struct {
	mock.Mock
}

type MockMigrationInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrationInterface) EXPECT() *MockMigrationInterface_Expecter {
	return &MockMigrationInterface_Expecter{mock: &_m.Mock}
}

// Down provides a mock function for the type MockMigrationInterface
func (_mock *MockMigrationInterface) Down(db mongo.MongoDatabase) error {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(mongo.MongoDatabase) error); ok {
		r0 = returnFunc(db)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrationInterface_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type MockMigrationInterface_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - db mongo.MongoDatabase
func (_e *MockMigrationInterface_Expecter) Down(db interface{}) *MockMigrationInterface_Down_Call {
	return &MockMigrationInterface_Down_Call{Call: _e.mock.On("Down", db)}
}

func (_c *MockMigrationInterface_Down_Call) Run(run func(db mongo.MongoDatabase)) *MockMigrationInterface_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 mongo.MongoDatabase
		if args[0] != nil {
			arg0 = args[0].(mongo.MongoDatabase)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMigrationInterface_Down_Call) Return(err error) *MockMigrationInterface_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrationInterface_Down_Call) RunAndReturn(run func(db mongo.MongoDatabase) error) *MockMigrationInterface_Down_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockMigrationInterface
func (_mock *MockMigrationInterface) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMigrationInterface_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockMigrationInterface_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockMigrationInterface_Expecter) Name() *MockMigrationInterface_Name_Call {
	return &MockMigrationInterface_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockMigrationInterface_Name_Call) Run(run func()) *MockMigrationInterface_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMigrationInterface_Name_Call) Return(s string) *MockMigrationInterface_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMigrationInterface_Name_Call) RunAndReturn(run func() string) *MockMigrationInterface_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type MockMigrationInterface
func (_mock *MockMigrationInterface) Up(db mongo.MongoDatabase) error {
	ret := _mock.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(mongo.MongoDatabase) error); ok {
		r0 = returnFunc(db)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrationInterface_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockMigrationInterface_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - db mongo.MongoDatabase
func (_e *MockMigrationInterface_Expecter) Up(db interface{}) *MockMigrationInterface_Up_Call {
	return &MockMigrationInterface_Up_Call{Call: _e.mock.On("Up", db)}
}

func (_c *MockMigrationInterface_Up_Call) Run(run func(db mongo.MongoDatabase)) *MockMigrationInterface_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 mongo.MongoDatabase
		if args[0] != nil {
			arg0 = args[0].(mongo.MongoDatabase)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMigrationInterface_Up_Call) Return(err error) *MockMigrationInterface_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrationInterface_Up_Call) RunAndReturn(run func(db mongo.MongoDatabase) error) *MockMigrationInterface_Up_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockMigrationInterface
func (_mock *MockMigrationInterface) Version() *version.Version {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 *version.Version
	if returnFunc, ok := ret.Get(0).(func() *version.Version); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*version.Version)
		}
	}
	return r0
}

// MockMigrationInterface_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockMigrationInterface_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockMigrationInterface_Expecter) Version() *MockMigrationInterface_Version_Call {
	return &MockMigrationInterface_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockMigrationInterface_Version_Call) Run(run func()) *MockMigrationInterface_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMigrationInterface_Version_Call) Return(version1 *version.Version) *MockMigrationInterface_Version_Call {
	_c.Call.Return(version1)
	return _c
}

func (_c *MockMigrationInterface_Version_Call) RunAndReturn(run func() *version.Version) *MockMigrationInterface_Version_Call {
	_c.Call.Return(run)
	return _c
}
