// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package migration

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMigrationRepositoryInterface creates a new instance of MockMigrationRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrationRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrationRepositoryInterface {
	mock := &MockMigrationRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMigrationRepositoryInterface is an autogenerated mock type for the MigrationRepositoryInterface type
type MockMigrationRepositoryInterface struct {
	mock.Mock
}

type MockMigrationRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrationRepositoryInterface) EXPECT() *MockMigrationRepositoryInterface_Expecter {
	return &MockMigrationRepositoryInterface_Expecter{mock: &_m.Mock}
}

// LoadMigrations provides a mock function for the type MockMigrationRepositoryInterface
func (_mock *MockMigrationRepositoryInterface) LoadMigrations() []MigrationInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadMigrations")
	}

	var r0 []MigrationInterface
	if returnFunc, ok := ret.Get(0).(func() []MigrationInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MigrationInterface)
		}
	}
	return r0
}

// MockMigrationRepositoryInterface_LoadMigrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadMigrations'
type MockMigrationRepositoryInterface_LoadMigrations_Call struct {
	*mock.Call
}

// LoadMigrations is a helper method to define mock.On call
func (_e *MockMigrationRepositoryInterface_Expecter) LoadMigrations() *MockMigrationRepositoryInterface_LoadMigrations_Call {
	return &MockMigrationRepositoryInterface_LoadMigrations_Call{Call: _e.mock.On("LoadMigrations")}
}

func (_c *MockMigrationRepositoryInterface_LoadMigrations_Call) Run(run func()) *MockMigrationRepositoryInterface_LoadMigrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMigrationRepositoryInterface_LoadMigrations_Call) Return(migrationInterfaces []MigrationInterface) *MockMigrationRepositoryInterface_LoadMigrations_Call {
	_c.Call.Return(migrationInterfaces)
	return _c
}

func (_c *MockMigrationRepositoryInterface_LoadMigrations_Call) RunAndReturn(run func() []MigrationInterface) *MockMigrationRepositoryInterface_LoadMigrations_Call {
	_c.Call.Return(run)
	return _c
}
