// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package migration

import (
	"github.com/mikelear/leartech-bus-common/pkg/mongo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMigrationManagerInterface creates a new instance of MockMigrationManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrationManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrationManagerInterface {
	mock := &MockMigrationManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMigrationManagerInterface is an autogenerated mock type for the MigrationManagerInterface type
type MockMigrationManagerInterface struct {
	mock.Mock
}

type MockMigrationManagerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrationManagerInterface) EXPECT() *MockMigrationManagerInterface_Expecter {
	return &MockMigrationManagerInterface_Expecter{mock: &_m.Mock}
}

// RunMigrations provides a mock function for the type MockMigrationManagerInterface
func (_mock *MockMigrationManagerInterface) RunMigrations(client *mongo.MongoClient, steps int) error {
	ret := _mock.Called(client, steps)

	if len(ret) == 0 {
		panic("no return value specified for RunMigrations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*mongo.MongoClient, int) error); ok {
		r0 = returnFunc(client, steps)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrationManagerInterface_RunMigrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunMigrations'
type MockMigrationManagerInterface_RunMigrations_Call struct {
	*mock.Call
}

// RunMigrations is a helper method to define mock.On call
//   - client *mongo.MongoClient
//   - steps int
func (_e *MockMigrationManagerInterface_Expecter) RunMigrations(client interface{}, steps interface{}) *MockMigrationManagerInterface_RunMigrations_Call {
	return &MockMigrationManagerInterface_RunMigrations_Call{Call: _e.mock.On("RunMigrations", client, steps)}
}

func (_c *MockMigrationManagerInterface_RunMigrations_Call) Run(run func(client *mongo.MongoClient, steps int)) *MockMigrationManagerInterface_RunMigrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mongo.MongoClient
		if args[0] != nil {
			arg0 = args[0].(*mongo.MongoClient)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigrationManagerInterface_RunMigrations_Call) Return(err error) *MockMigrationManagerInterface_RunMigrations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrationManagerInterface_RunMigrations_Call) RunAndReturn(run func(client *mongo.MongoClient, steps int) error) *MockMigrationManagerInterface_RunMigrations_Call {
	_c.Call.Return(run)
	return _c
}
