// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package migration

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNodeFactoryInterface creates a new instance of MockNodeFactoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeFactoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeFactoryInterface {
	mock := &MockNodeFactoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeFactoryInterface is an autogenerated mock type for the NodeFactoryInterface type
type MockNodeFactoryInterface struct {
	mock.Mock
}

type MockNodeFactoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeFactoryInterface) EXPECT() *MockNodeFactoryInterface_Expecter {
	return &MockNodeFactoryInterface_Expecter{mock: &_m.Mock}
}

// ParseAndSortMigrations provides a mock function for the type MockNodeFactoryInterface
func (_mock *MockNodeFactoryInterface) ParseAndSortMigrations(migrations []MigrationInterface, allMigrationModels []MigrationsModel) ([]MigrationNode, []MigrationNode, error) {
	ret := _mock.Called(migrations, allMigrationModels)

	if len(ret) == 0 {
		panic("no return value specified for ParseAndSortMigrations")
	}

	var r0 []MigrationNode
	var r1 []MigrationNode
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]MigrationInterface, []MigrationsModel) ([]MigrationNode, []MigrationNode, error)); ok {
		return returnFunc(migrations, allMigrationModels)
	}
	if returnFunc, ok := ret.Get(0).(func([]MigrationInterface, []MigrationsModel) []MigrationNode); ok {
		r0 = returnFunc(migrations, allMigrationModels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MigrationNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]MigrationInterface, []MigrationsModel) []MigrationNode); ok {
		r1 = returnFunc(migrations, allMigrationModels)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]MigrationNode)
		}
	}
	if returnFunc, ok := ret.Get(2).(func([]MigrationInterface, []MigrationsModel) error); ok {
		r2 = returnFunc(migrations, allMigrationModels)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNodeFactoryInterface_ParseAndSortMigrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAndSortMigrations'
type MockNodeFactoryInterface_ParseAndSortMigrations_Call struct {
	*mock.Call
}

// ParseAndSortMigrations is a helper method to define mock.On call
//   - migrations []MigrationInterface
//   - allMigrationModels []MigrationsModel
func (_e *MockNodeFactoryInterface_Expecter) ParseAndSortMigrations(migrations interface{}, allMigrationModels interface{}) *MockNodeFactoryInterface_ParseAndSortMigrations_Call {
	return &MockNodeFactoryInterface_ParseAndSortMigrations_Call{Call: _e.mock.On("ParseAndSortMigrations", migrations, allMigrationModels)}
}

func (_c *MockNodeFactoryInterface_ParseAndSortMigrations_Call) Run(run func(migrations []MigrationInterface, allMigrationModels []MigrationsModel)) *MockNodeFactoryInterface_ParseAndSortMigrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []MigrationInterface
		if args[0] != nil {
			arg0 = args[0].([]MigrationInterface)
		}
		var arg1 []MigrationsModel
		if args[1] != nil {
			arg1 = args[1].([]MigrationsModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeFactoryInterface_ParseAndSortMigrations_Call) Return(migrationNodes []MigrationNode, migrationNodes1 []MigrationNode, err error) *MockNodeFactoryInterface_ParseAndSortMigrations_Call {
	_c.Call.Return(migrationNodes, migrationNodes1, err)
	return _c
}

func (_c *MockNodeFactoryInterface_ParseAndSortMigrations_Call) RunAndReturn(run func(migrations []MigrationInterface, allMigrationModels []MigrationsModel) ([]MigrationNode, []MigrationNode, error)) *MockNodeFactoryInterface_ParseAndSortMigrations_Call {
	_c.Call.Return(run)
	return _c
}
