// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package random

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRandomnessGenerator creates a new instance of MockRandomnessGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRandomnessGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRandomnessGenerator {
	mock := &MockRandomnessGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRandomnessGenerator is an autogenerated mock type for the RandomnessGenerator type
type MockRandomnessGenerator struct {
	mock.Mock
}

type MockRandomnessGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRandomnessGenerator) EXPECT() *MockRandomnessGenerator_Expecter {
	return &MockRandomnessGenerator_Expecter{mock: &_m.Mock}
}

// NewString provides a mock function for the type MockRandomnessGenerator
func (_mock *MockRandomnessGenerator) NewString(length int) (string, error) {
	ret := _mock.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for NewString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (string, error)); ok {
		return returnFunc(length)
	}
	if returnFunc, ok := ret.Get(0).(func(int) string); ok {
		r0 = returnFunc(length)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(length)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRandomnessGenerator_NewString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewString'
type MockRandomnessGenerator_NewString_Call struct {
	*mock.Call
}

// NewString is a helper method to define mock.On call
//   - length int
func (_e *MockRandomnessGenerator_Expecter) NewString(length interface{}) *MockRandomnessGenerator_NewString_Call {
	return &MockRandomnessGenerator_NewString_Call{Call: _e.mock.On("NewString", length)}
}

func (_c *MockRandomnessGenerator_NewString_Call) Run(run func(length int)) *MockRandomnessGenerator_NewString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRandomnessGenerator_NewString_Call) Return(s string, err error) *MockRandomnessGenerator_NewString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRandomnessGenerator_NewString_Call) RunAndReturn(run func(length int) (string, error)) *MockRandomnessGenerator_NewString_Call {
	_c.Call.Return(run)
	return _c
}

// NewUUID provides a mock function for the type MockRandomnessGenerator
func (_mock *MockRandomnessGenerator) NewUUID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewUUID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockRandomnessGenerator_NewUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewUUID'
type MockRandomnessGenerator_NewUUID_Call struct {
	*mock.Call
}

// NewUUID is a helper method to define mock.On call
func (_e *MockRandomnessGenerator_Expecter) NewUUID() *MockRandomnessGenerator_NewUUID_Call {
	return &MockRandomnessGenerator_NewUUID_Call{Call: _e.mock.On("NewUUID")}
}

func (_c *MockRandomnessGenerator_NewUUID_Call) Run(run func()) *MockRandomnessGenerator_NewUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRandomnessGenerator_NewUUID_Call) Return(uUID uuid.UUID) *MockRandomnessGenerator_NewUUID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockRandomnessGenerator_NewUUID_Call) RunAndReturn(run func() uuid.UUID) *MockRandomnessGenerator_NewUUID_Call {
	_c.Call.Return(run)
	return _c
}
