// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache[T] {
	mock := &MockCache[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache[T any] struct {
	mock.Mock
}

type MockCache_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockCache[T]) EXPECT() *MockCache_Expecter[T] {
	return &MockCache_Expecter[T]{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCache
func (_mock *MockCache[T]) Delete(ctx context.Context, key string) {
	_mock.Called(ctx, key)
	return
}

// MockCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCache_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter[T]) Delete(ctx interface{}, key interface{}) *MockCache_Delete_Call[T] {
	return &MockCache_Delete_Call[T]{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockCache_Delete_Call[T]) Run(run func(ctx context.Context, key string)) *MockCache_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Delete_Call[T]) Return() *MockCache_Delete_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Delete_Call[T]) RunAndReturn(run func(ctx context.Context, key string)) *MockCache_Delete_Call[T] {
	_c.Run(run)
	return _c
}

// DeleteKeysMatching provides a mock function for the type MockCache
func (_mock *MockCache[T]) DeleteKeysMatching(ctx context.Context, pattern string) error {
	ret := _mock.Called(ctx, pattern)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeysMatching")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, pattern)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_DeleteKeysMatching_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeysMatching'
type MockCache_DeleteKeysMatching_Call[T any] struct {
	*mock.Call
}

// DeleteKeysMatching is a helper method to define mock.On call
//   - ctx context.Context
//   - pattern string
func (_e *MockCache_Expecter[T]) DeleteKeysMatching(ctx interface{}, pattern interface{}) *MockCache_DeleteKeysMatching_Call[T] {
	return &MockCache_DeleteKeysMatching_Call[T]{Call: _e.mock.On("DeleteKeysMatching", ctx, pattern)}
}

func (_c *MockCache_DeleteKeysMatching_Call[T]) Run(run func(ctx context.Context, pattern string)) *MockCache_DeleteKeysMatching_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_DeleteKeysMatching_Call[T]) Return(err error) *MockCache_DeleteKeysMatching_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_DeleteKeysMatching_Call[T]) RunAndReturn(run func(ctx context.Context, pattern string) error) *MockCache_DeleteKeysMatching_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache[T]) Get(ctx context.Context, key string) (T, bool) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 T
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (T, bool)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) T); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter[T]) Get(ctx interface{}, key interface{}) *MockCache_Get_Call[T] {
	return &MockCache_Get_Call[T]{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCache_Get_Call[T]) Run(run func(ctx context.Context, key string)) *MockCache_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call[T]) Return(value T, exist bool) *MockCache_Get_Call[T] {
	_c.Call.Return(value, exist)
	return _c
}

func (_c *MockCache_Get_Call[T]) RunAndReturn(run func(ctx context.Context, key string) (T, bool)) *MockCache_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCache
func (_mock *MockCache[T]) Set(ctx context.Context, key string, value T) {
	_mock.Called(ctx, key, value)
	return
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call[T any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value T
func (_e *MockCache_Expecter[T]) Set(ctx interface{}, key interface{}, value interface{}) *MockCache_Set_Call[T] {
	return &MockCache_Set_Call[T]{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockCache_Set_Call[T]) Run(run func(ctx context.Context, key string, value T)) *MockCache_Set_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 T
		if args[2] != nil {
			arg2 = args[2].(T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_Set_Call[T]) Return() *MockCache_Set_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Set_Call[T]) RunAndReturn(run func(ctx context.Context, key string, value T)) *MockCache_Set_Call[T] {
	_c.Run(run)
	return _c
}
