// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongo

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIndexUseCase creates a new instance of MockIndexUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexUseCase {
	mock := &MockIndexUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIndexUseCase is an autogenerated mock type for the IndexUseCase type
type MockIndexUseCase struct {
	mock.Mock
}

type MockIndexUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexUseCase) EXPECT() *MockIndexUseCase_Expecter {
	return &MockIndexUseCase_Expecter{mock: &_m.Mock}
}

// CreateIndexIfNotExist provides a mock function for the type MockIndexUseCase
func (_mock *MockIndexUseCase) CreateIndexIfNotExist(ctx context.Context, iv MongoIndexView, existingIndexNames []string, index MongoIndex) error {
	ret := _mock.Called(ctx, iv, existingIndexNames, index)

	if len(ret) == 0 {
		panic("no return value specified for CreateIndexIfNotExist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, MongoIndexView, []string, MongoIndex) error); ok {
		r0 = returnFunc(ctx, iv, existingIndexNames, index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexUseCase_CreateIndexIfNotExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIndexIfNotExist'
type MockIndexUseCase_CreateIndexIfNotExist_Call struct {
	*mock.Call
}

// CreateIndexIfNotExist is a helper method to define mock.On call
//   - ctx context.Context
//   - iv MongoIndexView
//   - existingIndexNames []string
//   - index MongoIndex
func (_e *MockIndexUseCase_Expecter) CreateIndexIfNotExist(ctx interface{}, iv interface{}, existingIndexNames interface{}, index interface{}) *MockIndexUseCase_CreateIndexIfNotExist_Call {
	return &MockIndexUseCase_CreateIndexIfNotExist_Call{Call: _e.mock.On("CreateIndexIfNotExist", ctx, iv, existingIndexNames, index)}
}

func (_c *MockIndexUseCase_CreateIndexIfNotExist_Call) Run(run func(ctx context.Context, iv MongoIndexView, existingIndexNames []string, index MongoIndex)) *MockIndexUseCase_CreateIndexIfNotExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 MongoIndexView
		if args[1] != nil {
			arg1 = args[1].(MongoIndexView)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 MongoIndex
		if args[3] != nil {
			arg3 = args[3].(MongoIndex)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIndexUseCase_CreateIndexIfNotExist_Call) Return(err error) *MockIndexUseCase_CreateIndexIfNotExist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexUseCase_CreateIndexIfNotExist_Call) RunAndReturn(run func(ctx context.Context, iv MongoIndexView, existingIndexNames []string, index MongoIndex) error) *MockIndexUseCase_CreateIndexIfNotExist_Call {
	_c.Call.Return(run)
	return _c
}

// GetExistingIndexes provides a mock function for the type MockIndexUseCase
func (_mock *MockIndexUseCase) GetExistingIndexes(ctx context.Context, iv MongoIndexView) ([]string, error) {
	ret := _mock.Called(ctx, iv)

	if len(ret) == 0 {
		panic("no return value specified for GetExistingIndexes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, MongoIndexView) ([]string, error)); ok {
		return returnFunc(ctx, iv)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, MongoIndexView) []string); ok {
		r0 = returnFunc(ctx, iv)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, MongoIndexView) error); ok {
		r1 = returnFunc(ctx, iv)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIndexUseCase_GetExistingIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExistingIndexes'
type MockIndexUseCase_GetExistingIndexes_Call struct {
	*mock.Call
}

// GetExistingIndexes is a helper method to define mock.On call
//   - ctx context.Context
//   - iv MongoIndexView
func (_e *MockIndexUseCase_Expecter) GetExistingIndexes(ctx interface{}, iv interface{}) *MockIndexUseCase_GetExistingIndexes_Call {
	return &MockIndexUseCase_GetExistingIndexes_Call{Call: _e.mock.On("GetExistingIndexes", ctx, iv)}
}

func (_c *MockIndexUseCase_GetExistingIndexes_Call) Run(run func(ctx context.Context, iv MongoIndexView)) *MockIndexUseCase_GetExistingIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 MongoIndexView
		if args[1] != nil {
			arg1 = args[1].(MongoIndexView)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIndexUseCase_GetExistingIndexes_Call) Return(strings []string, err error) *MockIndexUseCase_GetExistingIndexes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIndexUseCase_GetExistingIndexes_Call) RunAndReturn(run func(ctx context.Context, iv MongoIndexView) ([]string, error)) *MockIndexUseCase_GetExistingIndexes_Call {
	_c.Call.Return(run)
	return _c
}
