// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongo

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"go.mongodb.org/mongo-driver/v2/mongo/readpref"
)

// NewMockMongoClient creates a new instance of MockMongoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoClient {
	mock := &MockMongoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongoClient is an autogenerated mock type for the MongoClient type
type MockMongoClient struct {
	mock.Mock
}

type MockMongoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoClient) EXPECT() *MockMongoClient_Expecter {
	return &MockMongoClient_Expecter{mock: &_m.Mock}
}

// Database provides a mock function for the type MockMongoClient
func (_mock *MockMongoClient) Database(name string, opts ...options.Lister[options.DatabaseOptions]) MongoDatabase {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(name, opts)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 MongoDatabase
	if returnFunc, ok := ret.Get(0).(func(string, ...options.Lister[options.DatabaseOptions]) MongoDatabase); ok {
		r0 = returnFunc(name, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MongoDatabase)
		}
	}
	return r0
}

// MockMongoClient_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type MockMongoClient_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
//   - name string
//   - opts ...options.Lister[options.DatabaseOptions]
func (_e *MockMongoClient_Expecter) Database(name interface{}, opts ...interface{}) *MockMongoClient_Database_Call {
	return &MockMongoClient_Database_Call{Call: _e.mock.On("Database",
		append([]interface{}{name}, opts...)...)}
}

func (_c *MockMongoClient_Database_Call) Run(run func(name string, opts ...options.Lister[options.DatabaseOptions])) *MockMongoClient_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []options.Lister[options.DatabaseOptions]
		var variadicArgs []options.Lister[options.DatabaseOptions]
		if len(args) > 1 {
			variadicArgs = args[1].([]options.Lister[options.DatabaseOptions])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMongoClient_Database_Call) Return(mongoDatabase MongoDatabase) *MockMongoClient_Database_Call {
	_c.Call.Return(mongoDatabase)
	return _c
}

func (_c *MockMongoClient_Database_Call) RunAndReturn(run func(name string, opts ...options.Lister[options.DatabaseOptions]) MongoDatabase) *MockMongoClient_Database_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type MockMongoClient
func (_mock *MockMongoClient) Disconnect(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoClient_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockMongoClient_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMongoClient_Expecter) Disconnect(ctx interface{}) *MockMongoClient_Disconnect_Call {
	return &MockMongoClient_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx)}
}

func (_c *MockMongoClient_Disconnect_Call) Run(run func(ctx context.Context)) *MockMongoClient_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoClient_Disconnect_Call) Return(err error) *MockMongoClient_Disconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoClient_Disconnect_Call) RunAndReturn(run func(ctx context.Context) error) *MockMongoClient_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockMongoClient
func (_mock *MockMongoClient) Ping(ctx context.Context, rp *readpref.ReadPref) error {
	ret := _mock.Called(ctx, rp)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *readpref.ReadPref) error); ok {
		r0 = returnFunc(ctx, rp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockMongoClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - rp *readpref.ReadPref
func (_e *MockMongoClient_Expecter) Ping(ctx interface{}, rp interface{}) *MockMongoClient_Ping_Call {
	return &MockMongoClient_Ping_Call{Call: _e.mock.On("Ping", ctx, rp)}
}

func (_c *MockMongoClient_Ping_Call) Run(run func(ctx context.Context, rp *readpref.ReadPref)) *MockMongoClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *readpref.ReadPref
		if args[1] != nil {
			arg1 = args[1].(*readpref.ReadPref)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMongoClient_Ping_Call) Return(err error) *MockMongoClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoClient_Ping_Call) RunAndReturn(run func(ctx context.Context, rp *readpref.ReadPref) error) *MockMongoClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}
