// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongo

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMongoSingleResult creates a new instance of MockMongoSingleResult. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoSingleResult(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoSingleResult {
	mock := &MockMongoSingleResult{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongoSingleResult is an autogenerated mock type for the MongoSingleResult type
type MockMongoSingleResult struct {
	mock.Mock
}

type MockMongoSingleResult_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoSingleResult) EXPECT() *MockMongoSingleResult_Expecter {
	return &MockMongoSingleResult_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockMongoSingleResult
func (_mock *MockMongoSingleResult) Decode(v interface{}) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoSingleResult_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockMongoSingleResult_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - v interface{}
func (_e *MockMongoSingleResult_Expecter) Decode(v interface{}) *MockMongoSingleResult_Decode_Call {
	return &MockMongoSingleResult_Decode_Call{Call: _e.mock.On("Decode", v)}
}

func (_c *MockMongoSingleResult_Decode_Call) Run(run func(v interface{})) *MockMongoSingleResult_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoSingleResult_Decode_Call) Return(err error) *MockMongoSingleResult_Decode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoSingleResult_Decode_Call) RunAndReturn(run func(v interface{}) error) *MockMongoSingleResult_Decode_Call {
	_c.Call.Return(run)
	return _c
}
