// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongo

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// NewMockMongoCollection creates a new instance of MockMongoCollection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoCollection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoCollection {
	mock := &MockMongoCollection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongoCollection is an autogenerated mock type for the MongoCollection type
type MockMongoCollection struct {
	mock.Mock
}

type MockMongoCollection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoCollection) EXPECT() *MockMongoCollection_Expecter {
	return &MockMongoCollection_Expecter{mock: &_m.Mock}
}

// Aggregate provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) Aggregate(ctx context.Context, pipeline interface{}, opts ...options.Lister[options.AggregateOptions]) (MongoCursor, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, pipeline, opts)
	} else {
		tmpRet = _mock.Called(ctx, pipeline)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 MongoCursor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.AggregateOptions]) (MongoCursor, error)); ok {
		return returnFunc(ctx, pipeline, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.AggregateOptions]) MongoCursor); ok {
		r0 = returnFunc(ctx, pipeline, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MongoCursor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...options.Lister[options.AggregateOptions]) error); ok {
		r1 = returnFunc(ctx, pipeline, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_Aggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregate'
type MockMongoCollection_Aggregate_Call struct {
	*mock.Call
}

// Aggregate is a helper method to define mock.On call
//   - ctx context.Context
//   - pipeline interface{}
//   - opts ...options.Lister[options.AggregateOptions]
func (_e *MockMongoCollection_Expecter) Aggregate(ctx interface{}, pipeline interface{}, opts ...interface{}) *MockMongoCollection_Aggregate_Call {
	return &MockMongoCollection_Aggregate_Call{Call: _e.mock.On("Aggregate",
		append([]interface{}{ctx, pipeline}, opts...)...)}
}

func (_c *MockMongoCollection_Aggregate_Call) Run(run func(ctx context.Context, pipeline interface{}, opts ...options.Lister[options.AggregateOptions])) *MockMongoCollection_Aggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []options.Lister[options.AggregateOptions]
		var variadicArgs []options.Lister[options.AggregateOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.AggregateOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_Aggregate_Call) Return(mongoCursor MongoCursor, err error) *MockMongoCollection_Aggregate_Call {
	_c.Call.Return(mongoCursor, err)
	return _c
}

func (_c *MockMongoCollection_Aggregate_Call) RunAndReturn(run func(ctx context.Context, pipeline interface{}, opts ...options.Lister[options.AggregateOptions]) (MongoCursor, error)) *MockMongoCollection_Aggregate_Call {
	_c.Call.Return(run)
	return _c
}

// BulkWrite provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) BulkWrite(ctx context.Context, models []mongo.WriteModel, opts ...options.Lister[options.BulkWriteOptions]) (*mongo.BulkWriteResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, models, opts)
	} else {
		tmpRet = _mock.Called(ctx, models)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BulkWrite")
	}

	var r0 *mongo.BulkWriteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mongo.WriteModel, ...options.Lister[options.BulkWriteOptions]) (*mongo.BulkWriteResult, error)); ok {
		return returnFunc(ctx, models, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mongo.WriteModel, ...options.Lister[options.BulkWriteOptions]) *mongo.BulkWriteResult); ok {
		r0 = returnFunc(ctx, models, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.BulkWriteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []mongo.WriteModel, ...options.Lister[options.BulkWriteOptions]) error); ok {
		r1 = returnFunc(ctx, models, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_BulkWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkWrite'
type MockMongoCollection_BulkWrite_Call struct {
	*mock.Call
}

// BulkWrite is a helper method to define mock.On call
//   - ctx context.Context
//   - models []mongo.WriteModel
//   - opts ...options.Lister[options.BulkWriteOptions]
func (_e *MockMongoCollection_Expecter) BulkWrite(ctx interface{}, models interface{}, opts ...interface{}) *MockMongoCollection_BulkWrite_Call {
	return &MockMongoCollection_BulkWrite_Call{Call: _e.mock.On("BulkWrite",
		append([]interface{}{ctx, models}, opts...)...)}
}

func (_c *MockMongoCollection_BulkWrite_Call) Run(run func(ctx context.Context, models []mongo.WriteModel, opts ...options.Lister[options.BulkWriteOptions])) *MockMongoCollection_BulkWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []mongo.WriteModel
		if args[1] != nil {
			arg1 = args[1].([]mongo.WriteModel)
		}
		var arg2 []options.Lister[options.BulkWriteOptions]
		var variadicArgs []options.Lister[options.BulkWriteOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.BulkWriteOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_BulkWrite_Call) Return(bulkWriteResult *mongo.BulkWriteResult, err error) *MockMongoCollection_BulkWrite_Call {
	_c.Call.Return(bulkWriteResult, err)
	return _c
}

func (_c *MockMongoCollection_BulkWrite_Call) RunAndReturn(run func(ctx context.Context, models []mongo.WriteModel, opts ...options.Lister[options.BulkWriteOptions]) (*mongo.BulkWriteResult, error)) *MockMongoCollection_BulkWrite_Call {
	_c.Call.Return(run)
	return _c
}

// Clone provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) Clone(opts ...options.Lister[options.CollectionOptions]) *mongo.Collection {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(opts)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 *mongo.Collection
	if returnFunc, ok := ret.Get(0).(func(...options.Lister[options.CollectionOptions]) *mongo.Collection); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Collection)
		}
	}
	return r0
}

// MockMongoCollection_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockMongoCollection_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - opts ...options.Lister[options.CollectionOptions]
func (_e *MockMongoCollection_Expecter) Clone(opts ...interface{}) *MockMongoCollection_Clone_Call {
	return &MockMongoCollection_Clone_Call{Call: _e.mock.On("Clone",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockMongoCollection_Clone_Call) Run(run func(opts ...options.Lister[options.CollectionOptions])) *MockMongoCollection_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []options.Lister[options.CollectionOptions]
		var variadicArgs []options.Lister[options.CollectionOptions]
		if len(args) > 0 {
			variadicArgs = args[0].([]options.Lister[options.CollectionOptions])
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_Clone_Call) Return(collection *mongo.Collection) *MockMongoCollection_Clone_Call {
	_c.Call.Return(collection)
	return _c
}

func (_c *MockMongoCollection_Clone_Call) RunAndReturn(run func(opts ...options.Lister[options.CollectionOptions]) *mongo.Collection) *MockMongoCollection_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// CountDocuments provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) CountDocuments(ctx context.Context, filter interface{}, opts ...options.Lister[options.CountOptions]) (int64, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CountDocuments")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.CountOptions]) (int64, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.CountOptions]) int64); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...options.Lister[options.CountOptions]) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_CountDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountDocuments'
type MockMongoCollection_CountDocuments_Call struct {
	*mock.Call
}

// CountDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...options.Lister[options.CountOptions]
func (_e *MockMongoCollection_Expecter) CountDocuments(ctx interface{}, filter interface{}, opts ...interface{}) *MockMongoCollection_CountDocuments_Call {
	return &MockMongoCollection_CountDocuments_Call{Call: _e.mock.On("CountDocuments",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockMongoCollection_CountDocuments_Call) Run(run func(ctx context.Context, filter interface{}, opts ...options.Lister[options.CountOptions])) *MockMongoCollection_CountDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []options.Lister[options.CountOptions]
		var variadicArgs []options.Lister[options.CountOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.CountOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_CountDocuments_Call) Return(n int64, err error) *MockMongoCollection_CountDocuments_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMongoCollection_CountDocuments_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...options.Lister[options.CountOptions]) (int64, error)) *MockMongoCollection_CountDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIndexesIfNotExist provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) CreateIndexesIfNotExist(ctx context.Context, indexes []MongoIndex) error {
	ret := _mock.Called(ctx, indexes)

	if len(ret) == 0 {
		panic("no return value specified for CreateIndexesIfNotExist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []MongoIndex) error); ok {
		r0 = returnFunc(ctx, indexes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoCollection_CreateIndexesIfNotExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIndexesIfNotExist'
type MockMongoCollection_CreateIndexesIfNotExist_Call struct {
	*mock.Call
}

// CreateIndexesIfNotExist is a helper method to define mock.On call
//   - ctx context.Context
//   - indexes []MongoIndex
func (_e *MockMongoCollection_Expecter) CreateIndexesIfNotExist(ctx interface{}, indexes interface{}) *MockMongoCollection_CreateIndexesIfNotExist_Call {
	return &MockMongoCollection_CreateIndexesIfNotExist_Call{Call: _e.mock.On("CreateIndexesIfNotExist", ctx, indexes)}
}

func (_c *MockMongoCollection_CreateIndexesIfNotExist_Call) Run(run func(ctx context.Context, indexes []MongoIndex)) *MockMongoCollection_CreateIndexesIfNotExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []MongoIndex
		if args[1] != nil {
			arg1 = args[1].([]MongoIndex)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMongoCollection_CreateIndexesIfNotExist_Call) Return(err error) *MockMongoCollection_CreateIndexesIfNotExist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoCollection_CreateIndexesIfNotExist_Call) RunAndReturn(run func(ctx context.Context, indexes []MongoIndex) error) *MockMongoCollection_CreateIndexesIfNotExist_Call {
	_c.Call.Return(run)
	return _c
}

// Database provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) Database() *mongo.Database {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 *mongo.Database
	if returnFunc, ok := ret.Get(0).(func() *mongo.Database); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Database)
		}
	}
	return r0
}

// MockMongoCollection_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type MockMongoCollection_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
func (_e *MockMongoCollection_Expecter) Database() *MockMongoCollection_Database_Call {
	return &MockMongoCollection_Database_Call{Call: _e.mock.On("Database")}
}

func (_c *MockMongoCollection_Database_Call) Run(run func()) *MockMongoCollection_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoCollection_Database_Call) Return(database *mongo.Database) *MockMongoCollection_Database_Call {
	_c.Call.Return(database)
	return _c
}

func (_c *MockMongoCollection_Database_Call) RunAndReturn(run func() *mongo.Database) *MockMongoCollection_Database_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) DeleteMany(ctx context.Context, filter any, opts ...options.Lister[options.DeleteManyOptions]) (*mongo.DeleteResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Lister[options.DeleteManyOptions]) (*mongo.DeleteResult, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Lister[options.DeleteManyOptions]) *mongo.DeleteResult); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, ...options.Lister[options.DeleteManyOptions]) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockMongoCollection_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - opts ...options.Lister[options.DeleteManyOptions]
func (_e *MockMongoCollection_Expecter) DeleteMany(ctx interface{}, filter interface{}, opts ...interface{}) *MockMongoCollection_DeleteMany_Call {
	return &MockMongoCollection_DeleteMany_Call{Call: _e.mock.On("DeleteMany",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockMongoCollection_DeleteMany_Call) Run(run func(ctx context.Context, filter any, opts ...options.Lister[options.DeleteManyOptions])) *MockMongoCollection_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []options.Lister[options.DeleteManyOptions]
		var variadicArgs []options.Lister[options.DeleteManyOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.DeleteManyOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_DeleteMany_Call) Return(deleteResult *mongo.DeleteResult, err error) *MockMongoCollection_DeleteMany_Call {
	_c.Call.Return(deleteResult, err)
	return _c
}

func (_c *MockMongoCollection_DeleteMany_Call) RunAndReturn(run func(ctx context.Context, filter any, opts ...options.Lister[options.DeleteManyOptions]) (*mongo.DeleteResult, error)) *MockMongoCollection_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOne provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) DeleteOne(ctx context.Context, filter interface{}, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteOne")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.DeleteOneOptions]) *mongo.DeleteResult); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...options.Lister[options.DeleteOneOptions]) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_DeleteOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOne'
type MockMongoCollection_DeleteOne_Call struct {
	*mock.Call
}

// DeleteOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...options.Lister[options.DeleteOneOptions]
func (_e *MockMongoCollection_Expecter) DeleteOne(ctx interface{}, filter interface{}, opts ...interface{}) *MockMongoCollection_DeleteOne_Call {
	return &MockMongoCollection_DeleteOne_Call{Call: _e.mock.On("DeleteOne",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockMongoCollection_DeleteOne_Call) Run(run func(ctx context.Context, filter interface{}, opts ...options.Lister[options.DeleteOneOptions])) *MockMongoCollection_DeleteOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []options.Lister[options.DeleteOneOptions]
		var variadicArgs []options.Lister[options.DeleteOneOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.DeleteOneOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_DeleteOne_Call) Return(deleteResult *mongo.DeleteResult, err error) *MockMongoCollection_DeleteOne_Call {
	_c.Call.Return(deleteResult, err)
	return _c
}

func (_c *MockMongoCollection_DeleteOne_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...options.Lister[options.DeleteOneOptions]) (*mongo.DeleteResult, error)) *MockMongoCollection_DeleteOne_Call {
	_c.Call.Return(run)
	return _c
}

// Distinct provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) Distinct(ctx context.Context, fieldName string, filter any, opts ...options.Lister[options.DistinctOptions]) *mongo.DistinctResult {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, fieldName, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, fieldName, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Distinct")
	}

	var r0 *mongo.DistinctResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...options.Lister[options.DistinctOptions]) *mongo.DistinctResult); ok {
		r0 = returnFunc(ctx, fieldName, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DistinctResult)
		}
	}
	return r0
}

// MockMongoCollection_Distinct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Distinct'
type MockMongoCollection_Distinct_Call struct {
	*mock.Call
}

// Distinct is a helper method to define mock.On call
//   - ctx context.Context
//   - fieldName string
//   - filter any
//   - opts ...options.Lister[options.DistinctOptions]
func (_e *MockMongoCollection_Expecter) Distinct(ctx interface{}, fieldName interface{}, filter interface{}, opts ...interface{}) *MockMongoCollection_Distinct_Call {
	return &MockMongoCollection_Distinct_Call{Call: _e.mock.On("Distinct",
		append([]interface{}{ctx, fieldName, filter}, opts...)...)}
}

func (_c *MockMongoCollection_Distinct_Call) Run(run func(ctx context.Context, fieldName string, filter any, opts ...options.Lister[options.DistinctOptions])) *MockMongoCollection_Distinct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []options.Lister[options.DistinctOptions]
		var variadicArgs []options.Lister[options.DistinctOptions]
		if len(args) > 3 {
			variadicArgs = args[3].([]options.Lister[options.DistinctOptions])
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_Distinct_Call) Return(distinctResult *mongo.DistinctResult) *MockMongoCollection_Distinct_Call {
	_c.Call.Return(distinctResult)
	return _c
}

func (_c *MockMongoCollection_Distinct_Call) RunAndReturn(run func(ctx context.Context, fieldName string, filter any, opts ...options.Lister[options.DistinctOptions]) *mongo.DistinctResult) *MockMongoCollection_Distinct_Call {
	_c.Call.Return(run)
	return _c
}

// Drop provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) Drop(ctx context.Context, opts ...options.Lister[options.DropCollectionOptions]) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Drop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Lister[options.DropCollectionOptions]) error); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoCollection_Drop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drop'
type MockMongoCollection_Drop_Call struct {
	*mock.Call
}

// Drop is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...options.Lister[options.DropCollectionOptions]
func (_e *MockMongoCollection_Expecter) Drop(ctx interface{}, opts ...interface{}) *MockMongoCollection_Drop_Call {
	return &MockMongoCollection_Drop_Call{Call: _e.mock.On("Drop",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockMongoCollection_Drop_Call) Run(run func(ctx context.Context, opts ...options.Lister[options.DropCollectionOptions])) *MockMongoCollection_Drop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []options.Lister[options.DropCollectionOptions]
		var variadicArgs []options.Lister[options.DropCollectionOptions]
		if len(args) > 1 {
			variadicArgs = args[1].([]options.Lister[options.DropCollectionOptions])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_Drop_Call) Return(err error) *MockMongoCollection_Drop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoCollection_Drop_Call) RunAndReturn(run func(ctx context.Context, opts ...options.Lister[options.DropCollectionOptions]) error) *MockMongoCollection_Drop_Call {
	_c.Call.Return(run)
	return _c
}

// EstimatedDocumentCount provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) EstimatedDocumentCount(ctx context.Context, opts ...options.Lister[options.EstimatedDocumentCountOptions]) (int64, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EstimatedDocumentCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Lister[options.EstimatedDocumentCountOptions]) (int64, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Lister[options.EstimatedDocumentCountOptions]) int64); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...options.Lister[options.EstimatedDocumentCountOptions]) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_EstimatedDocumentCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimatedDocumentCount'
type MockMongoCollection_EstimatedDocumentCount_Call struct {
	*mock.Call
}

// EstimatedDocumentCount is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...options.Lister[options.EstimatedDocumentCountOptions]
func (_e *MockMongoCollection_Expecter) EstimatedDocumentCount(ctx interface{}, opts ...interface{}) *MockMongoCollection_EstimatedDocumentCount_Call {
	return &MockMongoCollection_EstimatedDocumentCount_Call{Call: _e.mock.On("EstimatedDocumentCount",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockMongoCollection_EstimatedDocumentCount_Call) Run(run func(ctx context.Context, opts ...options.Lister[options.EstimatedDocumentCountOptions])) *MockMongoCollection_EstimatedDocumentCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []options.Lister[options.EstimatedDocumentCountOptions]
		var variadicArgs []options.Lister[options.EstimatedDocumentCountOptions]
		if len(args) > 1 {
			variadicArgs = args[1].([]options.Lister[options.EstimatedDocumentCountOptions])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_EstimatedDocumentCount_Call) Return(n int64, err error) *MockMongoCollection_EstimatedDocumentCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMongoCollection_EstimatedDocumentCount_Call) RunAndReturn(run func(ctx context.Context, opts ...options.Lister[options.EstimatedDocumentCountOptions]) (int64, error)) *MockMongoCollection_EstimatedDocumentCount_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) Find(ctx context.Context, filter interface{}, opts ...options.Lister[options.FindOptions]) (MongoCursor, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 MongoCursor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.FindOptions]) (MongoCursor, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.FindOptions]) MongoCursor); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MongoCursor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...options.Lister[options.FindOptions]) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockMongoCollection_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...options.Lister[options.FindOptions]
func (_e *MockMongoCollection_Expecter) Find(ctx interface{}, filter interface{}, opts ...interface{}) *MockMongoCollection_Find_Call {
	return &MockMongoCollection_Find_Call{Call: _e.mock.On("Find",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockMongoCollection_Find_Call) Run(run func(ctx context.Context, filter interface{}, opts ...options.Lister[options.FindOptions])) *MockMongoCollection_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []options.Lister[options.FindOptions]
		var variadicArgs []options.Lister[options.FindOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.FindOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_Find_Call) Return(mongoCursor MongoCursor, err error) *MockMongoCollection_Find_Call {
	_c.Call.Return(mongoCursor, err)
	return _c
}

func (_c *MockMongoCollection_Find_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...options.Lister[options.FindOptions]) (MongoCursor, error)) *MockMongoCollection_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) FindOne(ctx context.Context, filter interface{}, opts ...options.Lister[options.FindOneOptions]) MongoSingleResult {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 MongoSingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.FindOneOptions]) MongoSingleResult); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MongoSingleResult)
		}
	}
	return r0
}

// MockMongoCollection_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockMongoCollection_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...options.Lister[options.FindOneOptions]
func (_e *MockMongoCollection_Expecter) FindOne(ctx interface{}, filter interface{}, opts ...interface{}) *MockMongoCollection_FindOne_Call {
	return &MockMongoCollection_FindOne_Call{Call: _e.mock.On("FindOne",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockMongoCollection_FindOne_Call) Run(run func(ctx context.Context, filter interface{}, opts ...options.Lister[options.FindOneOptions])) *MockMongoCollection_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []options.Lister[options.FindOneOptions]
		var variadicArgs []options.Lister[options.FindOneOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.FindOneOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_FindOne_Call) Return(mongoSingleResult MongoSingleResult) *MockMongoCollection_FindOne_Call {
	_c.Call.Return(mongoSingleResult)
	return _c
}

func (_c *MockMongoCollection_FindOne_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...options.Lister[options.FindOneOptions]) MongoSingleResult) *MockMongoCollection_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneAndDelete provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) FindOneAndDelete(ctx context.Context, filter any, opts ...options.Lister[options.FindOneAndDeleteOptions]) *mongo.SingleResult {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndDelete")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Lister[options.FindOneAndDeleteOptions]) *mongo.SingleResult); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// MockMongoCollection_FindOneAndDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndDelete'
type MockMongoCollection_FindOneAndDelete_Call struct {
	*mock.Call
}

// FindOneAndDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - opts ...options.Lister[options.FindOneAndDeleteOptions]
func (_e *MockMongoCollection_Expecter) FindOneAndDelete(ctx interface{}, filter interface{}, opts ...interface{}) *MockMongoCollection_FindOneAndDelete_Call {
	return &MockMongoCollection_FindOneAndDelete_Call{Call: _e.mock.On("FindOneAndDelete",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockMongoCollection_FindOneAndDelete_Call) Run(run func(ctx context.Context, filter any, opts ...options.Lister[options.FindOneAndDeleteOptions])) *MockMongoCollection_FindOneAndDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []options.Lister[options.FindOneAndDeleteOptions]
		var variadicArgs []options.Lister[options.FindOneAndDeleteOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.FindOneAndDeleteOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_FindOneAndDelete_Call) Return(singleResult *mongo.SingleResult) *MockMongoCollection_FindOneAndDelete_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *MockMongoCollection_FindOneAndDelete_Call) RunAndReturn(run func(ctx context.Context, filter any, opts ...options.Lister[options.FindOneAndDeleteOptions]) *mongo.SingleResult) *MockMongoCollection_FindOneAndDelete_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneAndReplace provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) FindOneAndReplace(ctx context.Context, filter any, replacement any, opts ...options.Lister[options.FindOneAndReplaceOptions]) *mongo.SingleResult {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, replacement, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, replacement)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndReplace")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.FindOneAndReplaceOptions]) *mongo.SingleResult); ok {
		r0 = returnFunc(ctx, filter, replacement, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// MockMongoCollection_FindOneAndReplace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndReplace'
type MockMongoCollection_FindOneAndReplace_Call struct {
	*mock.Call
}

// FindOneAndReplace is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - replacement any
//   - opts ...options.Lister[options.FindOneAndReplaceOptions]
func (_e *MockMongoCollection_Expecter) FindOneAndReplace(ctx interface{}, filter interface{}, replacement interface{}, opts ...interface{}) *MockMongoCollection_FindOneAndReplace_Call {
	return &MockMongoCollection_FindOneAndReplace_Call{Call: _e.mock.On("FindOneAndReplace",
		append([]interface{}{ctx, filter, replacement}, opts...)...)}
}

func (_c *MockMongoCollection_FindOneAndReplace_Call) Run(run func(ctx context.Context, filter any, replacement any, opts ...options.Lister[options.FindOneAndReplaceOptions])) *MockMongoCollection_FindOneAndReplace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []options.Lister[options.FindOneAndReplaceOptions]
		var variadicArgs []options.Lister[options.FindOneAndReplaceOptions]
		if len(args) > 3 {
			variadicArgs = args[3].([]options.Lister[options.FindOneAndReplaceOptions])
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_FindOneAndReplace_Call) Return(singleResult *mongo.SingleResult) *MockMongoCollection_FindOneAndReplace_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *MockMongoCollection_FindOneAndReplace_Call) RunAndReturn(run func(ctx context.Context, filter any, replacement any, opts ...options.Lister[options.FindOneAndReplaceOptions]) *mongo.SingleResult) *MockMongoCollection_FindOneAndReplace_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneAndUpdate provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) FindOneAndUpdate(ctx context.Context, filter any, update any, opts ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, update, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdate")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// MockMongoCollection_FindOneAndUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndUpdate'
type MockMongoCollection_FindOneAndUpdate_Call struct {
	*mock.Call
}

// FindOneAndUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - filter any
//   - update any
//   - opts ...options.Lister[options.FindOneAndUpdateOptions]
func (_e *MockMongoCollection_Expecter) FindOneAndUpdate(ctx interface{}, filter interface{}, update interface{}, opts ...interface{}) *MockMongoCollection_FindOneAndUpdate_Call {
	return &MockMongoCollection_FindOneAndUpdate_Call{Call: _e.mock.On("FindOneAndUpdate",
		append([]interface{}{ctx, filter, update}, opts...)...)}
}

func (_c *MockMongoCollection_FindOneAndUpdate_Call) Run(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.FindOneAndUpdateOptions])) *MockMongoCollection_FindOneAndUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []options.Lister[options.FindOneAndUpdateOptions]
		var variadicArgs []options.Lister[options.FindOneAndUpdateOptions]
		if len(args) > 3 {
			variadicArgs = args[3].([]options.Lister[options.FindOneAndUpdateOptions])
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_FindOneAndUpdate_Call) Return(singleResult *mongo.SingleResult) *MockMongoCollection_FindOneAndUpdate_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *MockMongoCollection_FindOneAndUpdate_Call) RunAndReturn(run func(ctx context.Context, filter any, update any, opts ...options.Lister[options.FindOneAndUpdateOptions]) *mongo.SingleResult) *MockMongoCollection_FindOneAndUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Indexes provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) Indexes() MongoIndexView {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Indexes")
	}

	var r0 MongoIndexView
	if returnFunc, ok := ret.Get(0).(func() MongoIndexView); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MongoIndexView)
		}
	}
	return r0
}

// MockMongoCollection_Indexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Indexes'
type MockMongoCollection_Indexes_Call struct {
	*mock.Call
}

// Indexes is a helper method to define mock.On call
func (_e *MockMongoCollection_Expecter) Indexes() *MockMongoCollection_Indexes_Call {
	return &MockMongoCollection_Indexes_Call{Call: _e.mock.On("Indexes")}
}

func (_c *MockMongoCollection_Indexes_Call) Run(run func()) *MockMongoCollection_Indexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoCollection_Indexes_Call) Return(mongoIndexView MongoIndexView) *MockMongoCollection_Indexes_Call {
	_c.Call.Return(mongoIndexView)
	return _c
}

func (_c *MockMongoCollection_Indexes_Call) RunAndReturn(run func() MongoIndexView) *MockMongoCollection_Indexes_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) InsertMany(ctx context.Context, documents []interface{}, opts ...options.Lister[options.InsertManyOptions]) (*mongo.InsertManyResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, documents, opts)
	} else {
		tmpRet = _mock.Called(ctx, documents)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 *mongo.InsertManyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interface{}, ...options.Lister[options.InsertManyOptions]) (*mongo.InsertManyResult, error)); ok {
		return returnFunc(ctx, documents, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interface{}, ...options.Lister[options.InsertManyOptions]) *mongo.InsertManyResult); ok {
		r0 = returnFunc(ctx, documents, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertManyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []interface{}, ...options.Lister[options.InsertManyOptions]) error); ok {
		r1 = returnFunc(ctx, documents, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockMongoCollection_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []interface{}
//   - opts ...options.Lister[options.InsertManyOptions]
func (_e *MockMongoCollection_Expecter) InsertMany(ctx interface{}, documents interface{}, opts ...interface{}) *MockMongoCollection_InsertMany_Call {
	return &MockMongoCollection_InsertMany_Call{Call: _e.mock.On("InsertMany",
		append([]interface{}{ctx, documents}, opts...)...)}
}

func (_c *MockMongoCollection_InsertMany_Call) Run(run func(ctx context.Context, documents []interface{}, opts ...options.Lister[options.InsertManyOptions])) *MockMongoCollection_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []interface{}
		if args[1] != nil {
			arg1 = args[1].([]interface{})
		}
		var arg2 []options.Lister[options.InsertManyOptions]
		var variadicArgs []options.Lister[options.InsertManyOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.InsertManyOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_InsertMany_Call) Return(insertManyResult *mongo.InsertManyResult, err error) *MockMongoCollection_InsertMany_Call {
	_c.Call.Return(insertManyResult, err)
	return _c
}

func (_c *MockMongoCollection_InsertMany_Call) RunAndReturn(run func(ctx context.Context, documents []interface{}, opts ...options.Lister[options.InsertManyOptions]) (*mongo.InsertManyResult, error)) *MockMongoCollection_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOne provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) InsertOne(ctx context.Context, document interface{}, opts ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, document, opts)
	} else {
		tmpRet = _mock.Called(ctx, document)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertOne")
	}

	var r0 *mongo.InsertOneResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error)); ok {
		return returnFunc(ctx, document, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...options.Lister[options.InsertOneOptions]) *mongo.InsertOneResult); ok {
		r0 = returnFunc(ctx, document, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertOneResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...options.Lister[options.InsertOneOptions]) error); ok {
		r1 = returnFunc(ctx, document, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_InsertOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOne'
type MockMongoCollection_InsertOne_Call struct {
	*mock.Call
}

// InsertOne is a helper method to define mock.On call
//   - ctx context.Context
//   - document interface{}
//   - opts ...options.Lister[options.InsertOneOptions]
func (_e *MockMongoCollection_Expecter) InsertOne(ctx interface{}, document interface{}, opts ...interface{}) *MockMongoCollection_InsertOne_Call {
	return &MockMongoCollection_InsertOne_Call{Call: _e.mock.On("InsertOne",
		append([]interface{}{ctx, document}, opts...)...)}
}

func (_c *MockMongoCollection_InsertOne_Call) Run(run func(ctx context.Context, document interface{}, opts ...options.Lister[options.InsertOneOptions])) *MockMongoCollection_InsertOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []options.Lister[options.InsertOneOptions]
		var variadicArgs []options.Lister[options.InsertOneOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.InsertOneOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_InsertOne_Call) Return(insertOneResult *mongo.InsertOneResult, err error) *MockMongoCollection_InsertOne_Call {
	_c.Call.Return(insertOneResult, err)
	return _c
}

func (_c *MockMongoCollection_InsertOne_Call) RunAndReturn(run func(ctx context.Context, document interface{}, opts ...options.Lister[options.InsertOneOptions]) (*mongo.InsertOneResult, error)) *MockMongoCollection_InsertOne_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMongoCollection_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockMongoCollection_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockMongoCollection_Expecter) Name() *MockMongoCollection_Name_Call {
	return &MockMongoCollection_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockMongoCollection_Name_Call) Run(run func()) *MockMongoCollection_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoCollection_Name_Call) Return(s string) *MockMongoCollection_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMongoCollection_Name_Call) RunAndReturn(run func() string) *MockMongoCollection_Name_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceOne provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) ReplaceOne(ctx context.Context, filter interface{}, replacement interface{}, opts ...options.Lister[options.ReplaceOptions]) (*mongo.UpdateResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, replacement, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, replacement)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ReplaceOne")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...options.Lister[options.ReplaceOptions]) (*mongo.UpdateResult, error)); ok {
		return returnFunc(ctx, filter, replacement, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...options.Lister[options.ReplaceOptions]) *mongo.UpdateResult); ok {
		r0 = returnFunc(ctx, filter, replacement, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, interface{}, ...options.Lister[options.ReplaceOptions]) error); ok {
		r1 = returnFunc(ctx, filter, replacement, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_ReplaceOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceOne'
type MockMongoCollection_ReplaceOne_Call struct {
	*mock.Call
}

// ReplaceOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - replacement interface{}
//   - opts ...options.Lister[options.ReplaceOptions]
func (_e *MockMongoCollection_Expecter) ReplaceOne(ctx interface{}, filter interface{}, replacement interface{}, opts ...interface{}) *MockMongoCollection_ReplaceOne_Call {
	return &MockMongoCollection_ReplaceOne_Call{Call: _e.mock.On("ReplaceOne",
		append([]interface{}{ctx, filter, replacement}, opts...)...)}
}

func (_c *MockMongoCollection_ReplaceOne_Call) Run(run func(ctx context.Context, filter interface{}, replacement interface{}, opts ...options.Lister[options.ReplaceOptions])) *MockMongoCollection_ReplaceOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []options.Lister[options.ReplaceOptions]
		var variadicArgs []options.Lister[options.ReplaceOptions]
		if len(args) > 3 {
			variadicArgs = args[3].([]options.Lister[options.ReplaceOptions])
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_ReplaceOne_Call) Return(updateResult *mongo.UpdateResult, err error) *MockMongoCollection_ReplaceOne_Call {
	_c.Call.Return(updateResult, err)
	return _c
}

func (_c *MockMongoCollection_ReplaceOne_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, replacement interface{}, opts ...options.Lister[options.ReplaceOptions]) (*mongo.UpdateResult, error)) *MockMongoCollection_ReplaceOne_Call {
	_c.Call.Return(run)
	return _c
}

// SearchIndexes provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) SearchIndexes() mongo.SearchIndexView {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SearchIndexes")
	}

	var r0 mongo.SearchIndexView
	if returnFunc, ok := ret.Get(0).(func() mongo.SearchIndexView); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(mongo.SearchIndexView)
	}
	return r0
}

// MockMongoCollection_SearchIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchIndexes'
type MockMongoCollection_SearchIndexes_Call struct {
	*mock.Call
}

// SearchIndexes is a helper method to define mock.On call
func (_e *MockMongoCollection_Expecter) SearchIndexes() *MockMongoCollection_SearchIndexes_Call {
	return &MockMongoCollection_SearchIndexes_Call{Call: _e.mock.On("SearchIndexes")}
}

func (_c *MockMongoCollection_SearchIndexes_Call) Run(run func()) *MockMongoCollection_SearchIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoCollection_SearchIndexes_Call) Return(searchIndexView mongo.SearchIndexView) *MockMongoCollection_SearchIndexes_Call {
	_c.Call.Return(searchIndexView)
	return _c
}

func (_c *MockMongoCollection_SearchIndexes_Call) RunAndReturn(run func() mongo.SearchIndexView) *MockMongoCollection_SearchIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) UpdateByID(ctx context.Context, id any, update any, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, id, update, opts)
	} else {
		tmpRet = _mock.Called(ctx, id, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error)); ok {
		return returnFunc(ctx, id, update, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, any, ...options.Lister[options.UpdateOneOptions]) *mongo.UpdateResult); ok {
		r0 = returnFunc(ctx, id, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, any, ...options.Lister[options.UpdateOneOptions]) error); ok {
		r1 = returnFunc(ctx, id, update, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockMongoCollection_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id any
//   - update any
//   - opts ...options.Lister[options.UpdateOneOptions]
func (_e *MockMongoCollection_Expecter) UpdateByID(ctx interface{}, id interface{}, update interface{}, opts ...interface{}) *MockMongoCollection_UpdateByID_Call {
	return &MockMongoCollection_UpdateByID_Call{Call: _e.mock.On("UpdateByID",
		append([]interface{}{ctx, id, update}, opts...)...)}
}

func (_c *MockMongoCollection_UpdateByID_Call) Run(run func(ctx context.Context, id any, update any, opts ...options.Lister[options.UpdateOneOptions])) *MockMongoCollection_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []options.Lister[options.UpdateOneOptions]
		var variadicArgs []options.Lister[options.UpdateOneOptions]
		if len(args) > 3 {
			variadicArgs = args[3].([]options.Lister[options.UpdateOneOptions])
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_UpdateByID_Call) Return(updateResult *mongo.UpdateResult, err error) *MockMongoCollection_UpdateByID_Call {
	_c.Call.Return(updateResult, err)
	return _c
}

func (_c *MockMongoCollection_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id any, update any, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error)) *MockMongoCollection_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMany provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) UpdateMany(ctx context.Context, filter interface{}, update interface{}, opts ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, update, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateMany")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error)); ok {
		return returnFunc(ctx, filter, update, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...options.Lister[options.UpdateManyOptions]) *mongo.UpdateResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, interface{}, ...options.Lister[options.UpdateManyOptions]) error); ok {
		r1 = returnFunc(ctx, filter, update, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_UpdateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMany'
type MockMongoCollection_UpdateMany_Call struct {
	*mock.Call
}

// UpdateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - update interface{}
//   - opts ...options.Lister[options.UpdateManyOptions]
func (_e *MockMongoCollection_Expecter) UpdateMany(ctx interface{}, filter interface{}, update interface{}, opts ...interface{}) *MockMongoCollection_UpdateMany_Call {
	return &MockMongoCollection_UpdateMany_Call{Call: _e.mock.On("UpdateMany",
		append([]interface{}{ctx, filter, update}, opts...)...)}
}

func (_c *MockMongoCollection_UpdateMany_Call) Run(run func(ctx context.Context, filter interface{}, update interface{}, opts ...options.Lister[options.UpdateManyOptions])) *MockMongoCollection_UpdateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []options.Lister[options.UpdateManyOptions]
		var variadicArgs []options.Lister[options.UpdateManyOptions]
		if len(args) > 3 {
			variadicArgs = args[3].([]options.Lister[options.UpdateManyOptions])
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_UpdateMany_Call) Return(updateResult *mongo.UpdateResult, err error) *MockMongoCollection_UpdateMany_Call {
	_c.Call.Return(updateResult, err)
	return _c
}

func (_c *MockMongoCollection_UpdateMany_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, update interface{}, opts ...options.Lister[options.UpdateManyOptions]) (*mongo.UpdateResult, error)) *MockMongoCollection_UpdateMany_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOne provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) UpdateOne(ctx context.Context, filter interface{}, update interface{}, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, update, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error)); ok {
		return returnFunc(ctx, filter, update, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...options.Lister[options.UpdateOneOptions]) *mongo.UpdateResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, interface{}, ...options.Lister[options.UpdateOneOptions]) error); ok {
		r1 = returnFunc(ctx, filter, update, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_UpdateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOne'
type MockMongoCollection_UpdateOne_Call struct {
	*mock.Call
}

// UpdateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - update interface{}
//   - opts ...options.Lister[options.UpdateOneOptions]
func (_e *MockMongoCollection_Expecter) UpdateOne(ctx interface{}, filter interface{}, update interface{}, opts ...interface{}) *MockMongoCollection_UpdateOne_Call {
	return &MockMongoCollection_UpdateOne_Call{Call: _e.mock.On("UpdateOne",
		append([]interface{}{ctx, filter, update}, opts...)...)}
}

func (_c *MockMongoCollection_UpdateOne_Call) Run(run func(ctx context.Context, filter interface{}, update interface{}, opts ...options.Lister[options.UpdateOneOptions])) *MockMongoCollection_UpdateOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []options.Lister[options.UpdateOneOptions]
		var variadicArgs []options.Lister[options.UpdateOneOptions]
		if len(args) > 3 {
			variadicArgs = args[3].([]options.Lister[options.UpdateOneOptions])
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_UpdateOne_Call) Return(updateResult *mongo.UpdateResult, err error) *MockMongoCollection_UpdateOne_Call {
	_c.Call.Return(updateResult, err)
	return _c
}

func (_c *MockMongoCollection_UpdateOne_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, update interface{}, opts ...options.Lister[options.UpdateOneOptions]) (*mongo.UpdateResult, error)) *MockMongoCollection_UpdateOne_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockMongoCollection
func (_mock *MockMongoCollection) Watch(ctx context.Context, pipeline any, opts ...options.Lister[options.ChangeStreamOptions]) (*mongo.ChangeStream, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, pipeline, opts)
	} else {
		tmpRet = _mock.Called(ctx, pipeline)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 *mongo.ChangeStream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Lister[options.ChangeStreamOptions]) (*mongo.ChangeStream, error)); ok {
		return returnFunc(ctx, pipeline, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...options.Lister[options.ChangeStreamOptions]) *mongo.ChangeStream); ok {
		r0 = returnFunc(ctx, pipeline, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.ChangeStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any, ...options.Lister[options.ChangeStreamOptions]) error); ok {
		r1 = returnFunc(ctx, pipeline, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoCollection_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockMongoCollection_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - pipeline any
//   - opts ...options.Lister[options.ChangeStreamOptions]
func (_e *MockMongoCollection_Expecter) Watch(ctx interface{}, pipeline interface{}, opts ...interface{}) *MockMongoCollection_Watch_Call {
	return &MockMongoCollection_Watch_Call{Call: _e.mock.On("Watch",
		append([]interface{}{ctx, pipeline}, opts...)...)}
}

func (_c *MockMongoCollection_Watch_Call) Run(run func(ctx context.Context, pipeline any, opts ...options.Lister[options.ChangeStreamOptions])) *MockMongoCollection_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []options.Lister[options.ChangeStreamOptions]
		var variadicArgs []options.Lister[options.ChangeStreamOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.ChangeStreamOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoCollection_Watch_Call) Return(changeStream *mongo.ChangeStream, err error) *MockMongoCollection_Watch_Call {
	_c.Call.Return(changeStream, err)
	return _c
}

func (_c *MockMongoCollection_Watch_Call) RunAndReturn(run func(ctx context.Context, pipeline any, opts ...options.Lister[options.ChangeStreamOptions]) (*mongo.ChangeStream, error)) *MockMongoCollection_Watch_Call {
	_c.Call.Return(run)
	return _c
}
