// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongo

import (
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// NewMockMongoDatabase creates a new instance of MockMongoDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoDatabase {
	mock := &MockMongoDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongoDatabase is an autogenerated mock type for the MongoDatabase type
type MockMongoDatabase struct {
	mock.Mock
}

type MockMongoDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoDatabase) EXPECT() *MockMongoDatabase_Expecter {
	return &MockMongoDatabase_Expecter{mock: &_m.Mock}
}

// Collection provides a mock function for the type MockMongoDatabase
func (_mock *MockMongoDatabase) Collection(name string, opts ...options.Lister[options.CollectionOptions]) MongoCollection {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(name, opts)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Collection")
	}

	var r0 MongoCollection
	if returnFunc, ok := ret.Get(0).(func(string, ...options.Lister[options.CollectionOptions]) MongoCollection); ok {
		r0 = returnFunc(name, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MongoCollection)
		}
	}
	return r0
}

// MockMongoDatabase_Collection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collection'
type MockMongoDatabase_Collection_Call struct {
	*mock.Call
}

// Collection is a helper method to define mock.On call
//   - name string
//   - opts ...options.Lister[options.CollectionOptions]
func (_e *MockMongoDatabase_Expecter) Collection(name interface{}, opts ...interface{}) *MockMongoDatabase_Collection_Call {
	return &MockMongoDatabase_Collection_Call{Call: _e.mock.On("Collection",
		append([]interface{}{name}, opts...)...)}
}

func (_c *MockMongoDatabase_Collection_Call) Run(run func(name string, opts ...options.Lister[options.CollectionOptions])) *MockMongoDatabase_Collection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []options.Lister[options.CollectionOptions]
		var variadicArgs []options.Lister[options.CollectionOptions]
		if len(args) > 1 {
			variadicArgs = args[1].([]options.Lister[options.CollectionOptions])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMongoDatabase_Collection_Call) Return(mongoCollection MongoCollection) *MockMongoDatabase_Collection_Call {
	_c.Call.Return(mongoCollection)
	return _c
}

func (_c *MockMongoDatabase_Collection_Call) RunAndReturn(run func(name string, opts ...options.Lister[options.CollectionOptions]) MongoCollection) *MockMongoDatabase_Collection_Call {
	_c.Call.Return(run)
	return _c
}
