// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongo

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMongoCursor creates a new instance of MockMongoCursor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoCursor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoCursor {
	mock := &MockMongoCursor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongoCursor is an autogenerated mock type for the MongoCursor type
type MockMongoCursor struct {
	mock.Mock
}

type MockMongoCursor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoCursor) EXPECT() *MockMongoCursor_Expecter {
	return &MockMongoCursor_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockMongoCursor
func (_mock *MockMongoCursor) All(ctx context.Context, results interface{}) error {
	ret := _mock.Called(ctx, results)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = returnFunc(ctx, results)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoCursor_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockMongoCursor_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
//   - results interface{}
func (_e *MockMongoCursor_Expecter) All(ctx interface{}, results interface{}) *MockMongoCursor_All_Call {
	return &MockMongoCursor_All_Call{Call: _e.mock.On("All", ctx, results)}
}

func (_c *MockMongoCursor_All_Call) Run(run func(ctx context.Context, results interface{})) *MockMongoCursor_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMongoCursor_All_Call) Return(err error) *MockMongoCursor_All_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoCursor_All_Call) RunAndReturn(run func(ctx context.Context, results interface{}) error) *MockMongoCursor_All_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockMongoCursor
func (_mock *MockMongoCursor) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoCursor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMongoCursor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMongoCursor_Expecter) Close(ctx interface{}) *MockMongoCursor_Close_Call {
	return &MockMongoCursor_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockMongoCursor_Close_Call) Run(run func(ctx context.Context)) *MockMongoCursor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoCursor_Close_Call) Return(err error) *MockMongoCursor_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoCursor_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockMongoCursor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Decode provides a mock function for the type MockMongoCursor
func (_mock *MockMongoCursor) Decode(v interface{}) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoCursor_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockMongoCursor_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - v interface{}
func (_e *MockMongoCursor_Expecter) Decode(v interface{}) *MockMongoCursor_Decode_Call {
	return &MockMongoCursor_Decode_Call{Call: _e.mock.On("Decode", v)}
}

func (_c *MockMongoCursor_Decode_Call) Run(run func(v interface{})) *MockMongoCursor_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoCursor_Decode_Call) Return(err error) *MockMongoCursor_Decode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoCursor_Decode_Call) RunAndReturn(run func(v interface{}) error) *MockMongoCursor_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockMongoCursor
func (_mock *MockMongoCursor) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoCursor_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockMongoCursor_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockMongoCursor_Expecter) Err() *MockMongoCursor_Err_Call {
	return &MockMongoCursor_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockMongoCursor_Err_Call) Run(run func()) *MockMongoCursor_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoCursor_Err_Call) Return(err error) *MockMongoCursor_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoCursor_Err_Call) RunAndReturn(run func() error) *MockMongoCursor_Err_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockMongoCursor
func (_mock *MockMongoCursor) ID() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockMongoCursor_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockMongoCursor_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockMongoCursor_Expecter) ID() *MockMongoCursor_ID_Call {
	return &MockMongoCursor_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockMongoCursor_ID_Call) Run(run func()) *MockMongoCursor_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoCursor_ID_Call) Return(n int64) *MockMongoCursor_ID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockMongoCursor_ID_Call) RunAndReturn(run func() int64) *MockMongoCursor_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockMongoCursor
func (_mock *MockMongoCursor) Next(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMongoCursor_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockMongoCursor_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMongoCursor_Expecter) Next(ctx interface{}) *MockMongoCursor_Next_Call {
	return &MockMongoCursor_Next_Call{Call: _e.mock.On("Next", ctx)}
}

func (_c *MockMongoCursor_Next_Call) Run(run func(ctx context.Context)) *MockMongoCursor_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoCursor_Next_Call) Return(b bool) *MockMongoCursor_Next_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMongoCursor_Next_Call) RunAndReturn(run func(ctx context.Context) bool) *MockMongoCursor_Next_Call {
	_c.Call.Return(run)
	return _c
}

// TryNext provides a mock function for the type MockMongoCursor
func (_mock *MockMongoCursor) TryNext(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TryNext")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMongoCursor_TryNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryNext'
type MockMongoCursor_TryNext_Call struct {
	*mock.Call
}

// TryNext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMongoCursor_Expecter) TryNext(ctx interface{}) *MockMongoCursor_TryNext_Call {
	return &MockMongoCursor_TryNext_Call{Call: _e.mock.On("TryNext", ctx)}
}

func (_c *MockMongoCursor_TryNext_Call) Run(run func(ctx context.Context)) *MockMongoCursor_TryNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoCursor_TryNext_Call) Return(b bool) *MockMongoCursor_TryNext_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMongoCursor_TryNext_Call) RunAndReturn(run func(ctx context.Context) bool) *MockMongoCursor_TryNext_Call {
	_c.Call.Return(run)
	return _c
}
