// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongo

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// NewMockMongoIndexView creates a new instance of MockMongoIndexView. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoIndexView(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoIndexView {
	mock := &MockMongoIndexView{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongoIndexView is an autogenerated mock type for the MongoIndexView type
type MockMongoIndexView struct {
	mock.Mock
}

type MockMongoIndexView_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoIndexView) EXPECT() *MockMongoIndexView_Expecter {
	return &MockMongoIndexView_Expecter{mock: &_m.Mock}
}

// CreateOne provides a mock function for the type MockMongoIndexView
func (_mock *MockMongoIndexView) CreateOne(ctx context.Context, model mongo.IndexModel, opts ...options.Lister[options.CreateIndexesOptions]) (string, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, model, opts)
	} else {
		tmpRet = _mock.Called(ctx, model)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateOne")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mongo.IndexModel, ...options.Lister[options.CreateIndexesOptions]) (string, error)); ok {
		return returnFunc(ctx, model, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mongo.IndexModel, ...options.Lister[options.CreateIndexesOptions]) string); ok {
		r0 = returnFunc(ctx, model, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mongo.IndexModel, ...options.Lister[options.CreateIndexesOptions]) error); ok {
		r1 = returnFunc(ctx, model, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoIndexView_CreateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOne'
type MockMongoIndexView_CreateOne_Call struct {
	*mock.Call
}

// CreateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - model mongo.IndexModel
//   - opts ...options.Lister[options.CreateIndexesOptions]
func (_e *MockMongoIndexView_Expecter) CreateOne(ctx interface{}, model interface{}, opts ...interface{}) *MockMongoIndexView_CreateOne_Call {
	return &MockMongoIndexView_CreateOne_Call{Call: _e.mock.On("CreateOne",
		append([]interface{}{ctx, model}, opts...)...)}
}

func (_c *MockMongoIndexView_CreateOne_Call) Run(run func(ctx context.Context, model mongo.IndexModel, opts ...options.Lister[options.CreateIndexesOptions])) *MockMongoIndexView_CreateOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mongo.IndexModel
		if args[1] != nil {
			arg1 = args[1].(mongo.IndexModel)
		}
		var arg2 []options.Lister[options.CreateIndexesOptions]
		var variadicArgs []options.Lister[options.CreateIndexesOptions]
		if len(args) > 2 {
			variadicArgs = args[2].([]options.Lister[options.CreateIndexesOptions])
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMongoIndexView_CreateOne_Call) Return(s string, err error) *MockMongoIndexView_CreateOne_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMongoIndexView_CreateOne_Call) RunAndReturn(run func(ctx context.Context, model mongo.IndexModel, opts ...options.Lister[options.CreateIndexesOptions]) (string, error)) *MockMongoIndexView_CreateOne_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMongoIndexView
func (_mock *MockMongoIndexView) List(ctx context.Context, opts ...options.Lister[options.ListIndexesOptions]) (*mongo.Cursor, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *mongo.Cursor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Lister[options.ListIndexesOptions]) (*mongo.Cursor, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...options.Lister[options.ListIndexesOptions]) *mongo.Cursor); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Cursor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...options.Lister[options.ListIndexesOptions]) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoIndexView_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMongoIndexView_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...options.Lister[options.ListIndexesOptions]
func (_e *MockMongoIndexView_Expecter) List(ctx interface{}, opts ...interface{}) *MockMongoIndexView_List_Call {
	return &MockMongoIndexView_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockMongoIndexView_List_Call) Run(run func(ctx context.Context, opts ...options.Lister[options.ListIndexesOptions])) *MockMongoIndexView_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []options.Lister[options.ListIndexesOptions]
		var variadicArgs []options.Lister[options.ListIndexesOptions]
		if len(args) > 1 {
			variadicArgs = args[1].([]options.Lister[options.ListIndexesOptions])
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMongoIndexView_List_Call) Return(cursor *mongo.Cursor, err error) *MockMongoIndexView_List_Call {
	_c.Call.Return(cursor, err)
	return _c
}

func (_c *MockMongoIndexView_List_Call) RunAndReturn(run func(ctx context.Context, opts ...options.Lister[options.ListIndexesOptions]) (*mongo.Cursor, error)) *MockMongoIndexView_List_Call {
	_c.Call.Return(run)
	return _c
}
