// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLocker creates a new instance of MockLocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocker {
	mock := &MockLocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocker is an autogenerated mock type for the Locker type
type MockLocker struct {
	mock.Mock
}

type MockLocker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocker) EXPECT() *MockLocker_Expecter {
	return &MockLocker_Expecter{mock: &_m.Mock}
}

// AcquireLock provides a mock function for the type MockLocker
func (_mock *MockLocker) AcquireLock(ctx context.Context, key string) bool {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for AcquireLock")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockLocker_AcquireLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireLock'
type MockLocker_AcquireLock_Call struct {
	*mock.Call
}

// AcquireLock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockLocker_Expecter) AcquireLock(ctx interface{}, key interface{}) *MockLocker_AcquireLock_Call {
	return &MockLocker_AcquireLock_Call{Call: _e.mock.On("AcquireLock", ctx, key)}
}

func (_c *MockLocker_AcquireLock_Call) Run(run func(ctx context.Context, key string)) *MockLocker_AcquireLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocker_AcquireLock_Call) Return(b bool) *MockLocker_AcquireLock_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockLocker_AcquireLock_Call) RunAndReturn(run func(ctx context.Context, key string) bool) *MockLocker_AcquireLock_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseLock provides a mock function for the type MockLocker
func (_mock *MockLocker) ReleaseLock(ctx context.Context, key string) {
	_mock.Called(ctx, key)
	return
}

// MockLocker_ReleaseLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseLock'
type MockLocker_ReleaseLock_Call struct {
	*mock.Call
}

// ReleaseLock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockLocker_Expecter) ReleaseLock(ctx interface{}, key interface{}) *MockLocker_ReleaseLock_Call {
	return &MockLocker_ReleaseLock_Call{Call: _e.mock.On("ReleaseLock", ctx, key)}
}

func (_c *MockLocker_ReleaseLock_Call) Run(run func(ctx context.Context, key string)) *MockLocker_ReleaseLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocker_ReleaseLock_Call) Return() *MockLocker_ReleaseLock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLocker_ReleaseLock_Call) RunAndReturn(run func(ctx context.Context, key string)) *MockLocker_ReleaseLock_Call {
	_c.Run(run)
	return _c
}

// TryFunc provides a mock function for the type MockLocker
func (_mock *MockLocker) TryFunc(ctx context.Context, key string, fn func() error) (bool, error) {
	ret := _mock.Called(ctx, key, fn)

	if len(ret) == 0 {
		panic("no return value specified for TryFunc")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func() error) (bool, error)); ok {
		return returnFunc(ctx, key, fn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func() error) bool); ok {
		r0 = returnFunc(ctx, key, fn)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, func() error) error); ok {
		r1 = returnFunc(ctx, key, fn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocker_TryFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryFunc'
type MockLocker_TryFunc_Call struct {
	*mock.Call
}

// TryFunc is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - fn func() error
func (_e *MockLocker_Expecter) TryFunc(ctx interface{}, key interface{}, fn interface{}) *MockLocker_TryFunc_Call {
	return &MockLocker_TryFunc_Call{Call: _e.mock.On("TryFunc", ctx, key, fn)}
}

func (_c *MockLocker_TryFunc_Call) Run(run func(ctx context.Context, key string, fn func() error)) *MockLocker_TryFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func() error
		if args[2] != nil {
			arg2 = args[2].(func() error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLocker_TryFunc_Call) Return(b bool, err error) *MockLocker_TryFunc_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockLocker_TryFunc_Call) RunAndReturn(run func(ctx context.Context, key string, fn func() error) (bool, error)) *MockLocker_TryFunc_Call {
	_c.Call.Return(run)
	return _c
}
